title: tech-pionners
description: tech-pioneer 캡스톤 디자인 개발일지, 회의록 정리 블로그
theme: just-the-docs

url: https://tech-pioneers.github.io/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
